export const axeConfig = {
  rules: {
    // Level A
    "color-contrast": { enabled: true },
    "document-title": { enabled: true },
    "html-has-lang": { enabled: true },
    "html-lang-valid": { enabled: true },
    "landmark-one-main": { enabled: true },
    "page-has-heading-one": { enabled: true },
    region: { enabled: true },
    "skip-link": { enabled: true },

    // Level AA
    "color-contrast-enhanced": { enabled: true },
    "focus-order-semantics": { enabled: true },
    "heading-order": { enabled: true },
    label: { enabled: true },
    "landmark-unique": { enabled: true },
    list: { enabled: true },
    listitem: { enabled: true },
    "meta-viewport": { enabled: true },
    "page-has-main": { enabled: true },
    "presentation-role-conflict": { enabled: true },
    "role-img-alt": { enabled: true },
    "scope-attr-valid": { enabled: true },
    "table-duplicate-name": { enabled: true },
    "table-fake-caption": { enabled: true },
    "td-has-header": { enabled: true },
    "th-has-data-cells": { enabled: true },
    "valid-lang": { enabled: true },

    //Others
    "button-name": { enabled: true },
    "input-button-name": { enabled: true },
    "link-name": { enabled: true },
    "image-alt": { enabled: true },
    "form-field-multiple-labels": { enabled: true },
    "form-fieldset": { enabled: true },
    "form-field-group": { enabled: true },
    checkboxgroup: { enabled: true },
    radiogroup: { enabled: true },
    "select-name": { enabled: true },
    "text-input-missing-label": { enabled: true },
    "aria-allowed-attr": { enabled: true },
    "aria-allowed-role": { enabled: true },
    "aria-command-name": { enabled: true },
    "aria-hidden-body": { enabled: true },
    "aria-hidden-focus": { enabled: true },
    "aria-input-field-name": { enabled: true },
    "aria-required-attr": { enabled: true },
    "aria-required-children": { enabled: true },
    "aria-required-parent": { enabled: true },
    "aria-roles": { enabled: true },
    "aria-valid-attr-value": { enabled: true },
    "aria-valid-attr": { enabled: true },
    "duplicate-id": { enabled: true },
    "duplicate-id-active": { enabled: true },
    "duplicate-id-aria": { enabled: true },
    "focusable-no-name": { enabled: true },
    "frame-title": { enabled: true },
    "frame-title-unique": { enabled: true },
    "heading-order": { enabled: true },
    "image-redundant-alt": { enabled: true },
    "label-content-name-mismatch": { enabled: true },
    "landmark-banner-is-top-level": { enabled: true },
    "landmark-complementary-is-top-level": { enabled: true },
    "landmark-contentinfo-is-top-level": { enabled: true },
    "landmark-main-is-top-level": { enabled: true },
    "landmark-no-duplicate-banner": { enabled: true },
    "landmark-no-duplicate-contentinfo": { enabled: true },
    "landmark-no-duplicate-main": { enabled: true },
    "landmark-unique": { enabled: true },
    "link-in-text-block": { enabled: true },
    list: { enabled: true },
    listitem: { enabled: true },
    marquee: { enabled: true },
    "meta-refresh": { enabled: true },
    "meta-viewport": { enabled: true },
    "object-alt": { enabled: true },
    "page-has-main": { enabled: true },
    "presentation-role-conflict": { enabled: true },
    "role-img-alt": { enabled: true },
    "scope-attr-valid": { enabled: true },
    "server-side-image-map": { enabled: true },
    "svg-img-alt": { enabled: true },
    "table-duplicate-name": { enabled: true },
    "table-fake-caption": { enabled: true },
    "td-has-header": { enabled: true },
    "th-has-data-cells": { enabled: true },
    "valid-lang": { enabled: true },
    "video-caption": { enabled: true },
    "video-description": { enabled: true },
  },

  tags: ["wcag2a", "wcag2aa"],

  reporter: "v2",

  runOnly: {
    type: "tag",
    values: ["wcag2a", "wcag2aa"],
  },
};

export default axeConfig;
