services:
  # Main service for the index.html application
  - type: web
    name: rebel-ui-lib
    buildCommand: npm install && npm run build:app
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Service for Storybook
  - type: web
    name: rebel-ui-lib-storybook
    buildCommand: npm install && npm run build-storybook
    staticPublishPath: ./storybook-static
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 